"""El arte pixel de la cámara del CRT: retratos VGA como datos, no como PNGs.

Cada retrato es texto donde un caracter es un pixel: la letra elige un color
de la PALETA y el punto es transparente. Editar el arte es editar strings —
sin programa de dibujo, y el diff de git muestra qué pixel cambió. Es el
mismo truco que usa el juego hermano (cripta-arrayan, ``sprites.py``), pero
en 80×96 y con la paleta DB32 (DawnBringer 32): 32 colores pensados para el
look "VGA de los 90", con rampas de piel y de gris que permiten sombrear.

La ANIMACIÓN también son datos. Cada retrato tiene una ``base`` opaca (la
foto quieta, ojos abiertos y sin boca) y tres capas chicas con su posición:

    parpado       → los párpados cerrados; base.css los muestra al parpadear
    boca_cerrada  → la boca en reposo (visible por defecto)
    boca_abierta  → la boca hablando; alterna con la cerrada al streamear

El frontend pide todo por ``GET /api/retratos`` y pinta cada capa en su
propio <canvas> apilado, con las MISMAS clases CSS que animaban los SVG de
``retratos.js`` — el parpadeo y la charla ya estaban resueltos en base.css
y no se tocaron. Las fichas y el corcho siguen usando los retratos SVG: la
cámara de seguridad es digital y pixelada; la polaroid es una foto.

Los retratos nacieron rasterizando esos SVG (chromium headless + voto por
bloque + cuantización a DB32) y después se retocaron acá, a mano.
"""

# ── La paleta (DB32) ─────────────────────────────────────────────────────────
# Letra → hex, nemotécnicas en lo posible: k=negro (key), v=violeta nocturno,
# m=morado vino, M=marrón oscuro, B=marrón (Brown), o=naranja, t=tostado,
# F=piel (Flesh), y=amarillo, L=lima, g=verde (green), E=esmeralda, d=verde
# oscuro (dark), O=oliva, Z=pizarra, z=azul noche, A=azul mar, a=azul,
# C=celeste, c=cian, e=escarcha, w=blanco (white), S=plata (Silver),
# s=gris piedra, G=gris (Gray), h=humo, p=púrpura, r=rojo, R=rosado,
# P=rosa (Pink), n=oliva claro, u=ocre. El punto: transparente.

PALETA: dict[str, str] = {
    "k": "#000000", "v": "#222034", "m": "#45283c", "M": "#663931",
    "B": "#8f563b", "o": "#df7126", "t": "#d9a066", "F": "#eec39a",
    "y": "#fbf236", "L": "#99e550", "g": "#6abe30", "E": "#37946e",
    "d": "#4b692f", "O": "#524b24", "Z": "#323c39", "z": "#3f3f74",
    "A": "#306082", "a": "#5b6ee1", "C": "#639bff", "c": "#5fcde4",
    "e": "#cbdbfc", "w": "#ffffff", "S": "#9badb7", "s": "#847e87",
    "G": "#696a6a", "h": "#595652", "p": "#76428a", "r": "#ac3232",
    "R": "#d95763", "P": "#d77bba", "n": "#8f974a", "u": "#8a6f30",
}

TRANSPARENTE = "."

ANCHO, ALTO = 80, 96  # tamaño de la base; las capas son recortes posicionados

CAPAS_DE_ANIMACION = ("parpado", "boca_cerrada", "boca_abierta")

# ── Los retratos ─────────────────────────────────────────────────────────────
# La clave de cada retrato ES el id del sospechoso (un test vigila que estén
# los tres). En cada capa, "x"/"y" es la esquina superior izquierda del
# recorte dentro de la base.

RETRATOS: dict[str, dict] = {
    # ── Marta Iriarte — ingeniera jefa: carré con canas, lentes rectos ──────
    "marta": {
        "base": [
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "ttttttttttttttttttttttttttttttttttttttthhttttttttttttttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFhhhhhhhhhhFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFhhSSSSSSSSShhhFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFhhhhSSSSSSSShhhhFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFhhhhhhhhhhhhhhhhhhFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFhhhhhhhhhhhhhhhhhhhhFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFhhhhhhhhhhhhhhhhhhhhhhFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFhhhhhhhhhhhhhhhhhhhhhhFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFhhhhhhhhhhhhhhhhhhhhhhhhFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFhhhhhhhhtttttttthhhhhhhhFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "ttttttttttttttttttttttttttthhhhhhhtttttttttttthhhhhhtttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFhhhhhhtttttttttttttthhhhhhFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFhhhhhtttttttttttttttthhhhhFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFhhhhtttttttttttttttttthhhhFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhhhhhtttttttttttttttttthhhhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhhhhtttttttttttttttttttthhhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhhhhtttttttttttttttttttthhhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhhhtttttttttttttttttttttthhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhhhtttttttttttttttttttttthhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhhhttttttttZttttZtttttttthhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "tttttttttttttttttttttttttthhhtZZZZZZZZZttZZZZZZZZZthhhtttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhhhZZZZZZZZZttttZZZZZZZZZhhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhhhtZvvvvvvttttttvvvvvvvtthhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFhhvvvvvvvvvvvttttvvvvvvvvvvvhhFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFthvvvvtwwwwtvvvvvvtwwwwtvvvvhttFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFtthhhvvwwOOwwvvvvvvwwOOwwvvhhhttFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFtthhhvvwwkOwwvtBBtvwwkOwwvvthhhtFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFtthhhvvvvvvvvvtBBtvvvvvvvvvthhhtFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFthhhhtvvvvvvvvtBBtvvvvvvvvtthhhtFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFhhhhttttttttttBtttttttttttthhhFFFFFFFFFFFFFFFFFFFFFFFFF",
            "ttttttttttttttttttttttttthhhhttttttttttBttttttttttthhhhttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFhhhhttttttttttBttttttttttthhhhFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFhhhhtttttttttBBtBttttttttthhhhFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhshttttttttttBBBttttttttthhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhshtttttttttttttttttttttthhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhshtttttttttttttttttttttthhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhshhttttBttttttttttBtttthhhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhshhtttttttttttttttttttthhhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFhsshFttttttttttttttttttFhhhhFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFshhFFttttttttttttttttFFhhhFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "ttttttttttttttttttttttttttthhhhtttttttttttttttttthhhhttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFhFFttttttttttttttFFhFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBttttttBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "tttttttttttttttttttttttttttttttttttBBBBBBBBBBttttttttttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFZZBBBBBBBBBBZZFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFZZZZZBBBBBBZZZZZFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFZZZZZZZZBBZZZZZZZZFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFZZZZZZZZZZZZZZZZZZZZFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFZhhZZZZZZZZZhhZZZZZZZZZhhZFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFZZZhhhhZZZZZZhhhhZZZZZZhhhhZZZFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFZZZZZhhhhhZZZZhhhhhhZZZZhhhhhZZZZZFFFFFFFFFFFFFFFFFFFFFFF",
            "ttttttttttttttttttttttZZZZZZhhhhhhZZhhhZZhhhZZhhhhhhZZZZZZtttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFZZZZZZZhhhhhhhhhhhZZhhhhhhhhhhhZZZZZZZFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFZZZZZZZZhhhhhhhhhhhZZhhhhhhhhhhhZZZZZZZZFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFZZZZZZZZZhhhhhhhhhhhZZhhhhhhhhhhhZZZZZZZZZFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhhZZZZZZZZZZFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhhZZZZZZZZZZZFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhZZZZZZZZZZZZFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFZZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhsssZZZZZZZZZZFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFZZZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhFFZZZZZZZZZZZZFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFZZZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhFFFZZZZZZZZZZZFFFFFFFFFFFFFFF",
            "tttttttttttttttZZZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhZFFZZZZZZZZZZZttttttttttttttt",
            "FFFFFFFFFFFFFFZZZZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhZFFZZZZZZZZZZZZFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFZZZZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhZFFZZZZZZZZZZZZFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFZZZZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhZFFZZZZZZZZZZZZFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFZZZZZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhZZZZZZZZZZZZZZZZFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFZZZZZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhZZZZZZZZZZZZZZZZFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFZZZZZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhZZZZZZZZZZZZZZZZFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFZZZZZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhZZZZZZZZZZZZZZZZFFFFFFFFFFFFF",
            "FFFFFFFFFFFFZZZZZZZZZZZZZZZZZhhhhhhhhhhZZhhhhhhhhhhZZZZZZZZZZZZZZZZZFFFFFFFFFFFF",
            "FFFFFFFFFFFFZZZZZZZZZZZZZZZZZZhhhhhhhhhZZhhhhhhhhhhZZZZZZZZZZZZZZZZZFFFFFFFFFFFF",
            "FFFFFFFFFFFhZZZZZZZZZZZZZZZZZZhhhhhhhhhZZhhhhhhhhhhZZZZZZZZZZZZZZZZZhhFFFFFFFFFF",
            "FFFFFFFFFFhhZZZZZZZZZZZZZZZZZZhhhhhhhhhZZhhhhhhhhhZZZZZZZZZZZZZZZZZZhhhFFFFFFFFF",
        ],
        "capas": {
            "parpado": {"x": 31, "y": 38, "filas": [
                "tttttt......tttttt",
                "tttttt......tttttt",
                "tttttt......tttttt",
                ".tttt........tttt.",
            ]},
            "boca_cerrada": {"x": 35, "y": 52, "filas": [
                "BBBBBBBBBB",
                "BBBBBBBBBB",
            ]},
            "boca_abierta": {"x": 38, "y": 52, "filas": [
                "MMMM",
                "MMMM",
                "MMMM",
            ]},
        },
    },
    # ── Julián Funes — técnico junior: rulos, pecas, chaleco reflectivo ─────
    "julian": {
        "base": [
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "tttttttttttttttttttttttttttttttttttttvvvvvvvvttttttttttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvvvvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvvvvvvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvvvvvvvvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvvvvvvvvvvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvvvvvvvvvvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvvvvvvvvvvvvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvvvvvvvvvvvvvvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFF",
            "ttttttttttttttttttttttttvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvtttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvvvtvvvvvtttvvvttvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvtttttttttttttttvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvtttttttttttttttttvvvvvvFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvtttttttttttttttttttvvvvvFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFvvvvvvttttttttttttttttttttvvvvvvFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFvvvvvttttttttttttttttttttvvvvvFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFvvvttttZZZZZttttZZZZZttttvvvFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFtttZZZZZZZZttZZZZZZZZtttFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "ttttttttttttttttttttttttttttttZZZZZttZttttZttZZZZZtttttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFtttZZttttttttttttttttZZtttFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttttttttttttFeFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttttttttttttFeeFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFtttttttwwwwttttttttwwwwtttttteFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFtttttttwwOOwwttttttwwOOwwtttttttFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFtttttttwwOOwwttttttwwOOwwtttttttFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFttttttttwwwwtttBBtttwwwwttttttttFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFtttttttttttttttBBtttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFtttttttttttttttBBtttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFF",
            "tttttttttttttttttttttttttttttttttttttttBBttttttttttttttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFtFtttttttttttBBtttttttttttFtFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFttttBttttttBBtttttttBtttFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttBttttBBBBtttBtttttFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFtttttttttttBBtttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBttttttBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "ttttttttttttttttttttttttttttttttttttBBBBBBBBBttttttttttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFZZZZBBBBBBBBBZZZFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFZZZZrrBBBBBBBBrrZZZZFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFZZZZorrrrhhhhhhrrrroZZZZFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFZZZooorrrrhhhhhhrrrroooZZZFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFZhhoooorrrrhhhhhhrrrroooohhZFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "tttttttttttttttttttttttthhhooooooorrrrhhhhrrrrooooooohhhtttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFhhhhoooooooorrrrhhhhrrrroooooooohhhhFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFhhhhhoooooooorrrrhhhhrrrroooooooohhhhhFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFhhhhhoooooooooorrrrhhrrrroooooooooohhhhhFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFhhhhhooooooooooorrrrhhrrrrooooooooooohhhhhFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFhhhhhhooooooooooorrrrhhrrrrooooooooooohhhhhhFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFhhhhhoooooooooooorrrrrrrrrroooooooooooohhhhhFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFhhhhhhooooooooooooorrrrrrrrooooooooooooohhhhhhFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFhhhhhhoooooooooooooorrrrrrrroooooooooooooohhhhhhFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFhhhhhhFFFFFFFFFooooorrrrrrrroooooFFFFFFFFFhhhhhhFFFFFFFFFFFFFFFF",
            "ttttttttttttttthhhhhhhFFFFFFFFFFFFoohrrrrrrhooFFFFFFFFFFFFhhhhhhhttttttttttttttt",
            "FFFFFFFFFFFFFFFhhhhhhhFFFFFFFFFFFFooheeeeeehoooFFFFFFFFFFFhhhhhhhFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFhhhhhhhoooooooFFFFFoooheeseeehhooFFFFFooooooohhhhhhhFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFhhhhhhhoooooooooooooohhessseeehoooooooooooooohhhhhhhFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFhhhhhhhoooooooooooooohhessseeehoooooooooooooohhhhhhhFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFhhhhhhhhoooooooooooooohheeeeeeehoooooooooooooohhhhhhhhFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFhhhhhhhhoooooooooooooohheeeeeeehooooooooooooooohhhhhhhFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFhhhhhhhooooooooooooooohheeeeeeehooooooooooooooohhhhhhhFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFhhhhhhhooooooooooooooohheeeeeeehooooooooooooooohhhhhhhFFFFFFFFFFFFF",
            "FFFFFFFFFFFFhhhhhhhhooooooooooooooohhhhhhhhhhooooooooooooooohhhhhhhhFFFFFFFFFFFF",
            "FFFFFFFFFFFhhhhhhhhhooooooooooooooohhhhhhhhhhooooooooooooooohhhhhhhhhhFFFFFFFFFF",
            "FFFFFFFFFFhhhhhhhhhhooooooooooooooohhhhhhhhhhhoooooooooooooohhhhhhhhhhhFFFFFFFFF",
        ],
        "capas": {
            "parpado": {"x": 31, "y": 38, "filas": [
                "tttttt......tttttt",
                "tttttt......tttttt",
                "tttttt......tttttt",
                ".tttt........tttt.",
            ]},
            "boca_cerrada": {"x": 35, "y": 53, "filas": [
                "BBBBBBBBBB",
                ".BBBBBBBBB",
            ]},
            "boca_abierta": {"x": 38, "y": 52, "filas": [
                ".MM.",
                "MMMM",
                "MMMM",
                ".MM.",
            ]},
        },
    },
    # ── Silvia Roldán — Calidad y Seguridad: rodete, buzo azul, perlitas ────
    "silvia": {
        "base": [
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFvvFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFvmmmmvFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFmmmmmmmmFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFmmvvvvvvmmFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "tttttttttttttttttttttttttttttttttttvvvvvvvvvvttttttttttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvkkvvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvvvkkvvvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvvvvkkvvvvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFvvmmvvvvkkvvvvmmvvFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFvmmvvvvvkkvvvvvmmvFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFvmmvvvvvvkkvvvvvvmmvFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFvmmvvvvvvvkkvvvvvvvmmvFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFmmvvvvvvttttttvvvvvvmmFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "tttttttttttttttttttttttttttttmvvvvvttttttttttvvvvvmttttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFvmvvvttttttttttttttvvvmvFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvttttttttttttttttvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvvttttttttttttttttvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvttttttttttttttttttvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFvvvvttttttttttttttttttvvvvFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFvvvttttttttttttttttttttvvvFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFvvvttttttttttttttttttttvvvFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFvvvttttttttttttttttttttvvvFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFvvvttttmmmttttttttmmmttttvvFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "ttttttttttttttttttttttttttvvvtmmmmmmmmttttmmmmmmmmtvvvtttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFvvvtmmmmmmmmttttmmmmmmmmtvvvFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFvvvttttttttttttttttttttttvvvFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFtvvvttttttttttttttttttttttvvvtFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFtvvvtttwwwwttttttttwwwwtttvvvttFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFttvvvttwwZZwwttttttwwZZwwttvvvttFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFtttttttwwZZwwttBBttwwZZwwtttttttFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFttttttttwwwwtttBBtttwwwwttttttttFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFtttttttttttttttBBtttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttBBttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFF",
            "tttttttttttttttttttttttttwwttttttttttttBBttttttttttttwwttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFwwFtttttttttttBBtttttttttttFwwFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttBBBtttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFtttttttttttBBtttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFttttttttFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBttttttBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "ttttttttttttttttttttttttttttttttttttBBBBBBBBBttttttttttttttttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFzzBBBBBBBBBzFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFzzBBBBBBBBBzFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAzzBBBBBBBBzzAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAAAAzzzzzzzzzzzzAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAzzzzzzzzzzAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAzzzzzzAAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAAzzzzAAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFF",
            "ttttttttttttttttttttttAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAtttttttttttttttttttttt",
            "FFFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAeeAAAAAAAAAAAAAAAAAAAAAFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAAAAFFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAeeeeeeeeeeeeeAAFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAeeeeeeeeeeeeeAAFFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAeAAAeAAeAAAAAAFFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAeeeeeeeeeeeeeAAAFFFFFFFFFFFFFFF",
            "tttttttttttttttAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAeeeeeeeeeeeeeAAAttttttttttttttt",
            "FFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAeeeeeeeeeeeeeAAAAFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAAAAAAAFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAAAAAAAFFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAAAAAAAAFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAAAAAAAAFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAAAAAAAAFFFFFFFFFFFFF",
            "FFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAAAAAAAAFFFFFFFFFFFFF",
            "FFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAAAAAAAAAFFFFFFFFFFFF",
            "FFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAAAAAAAAAFFFFFFFFFFFF",
            "FFFFFFFFFFFhAAAAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAAAAAAAAAhhFFFFFFFFFF",
            "FFFFFFFFFFhhAAAAAAAAAAAAAAAAAAAAAAAAAAAzzAAAAAAAAAAAAAAAAAAAAAAAAAAAhhhFFFFFFFFF",
        ],
        "capas": {
            "parpado": {"x": 31, "y": 38, "filas": [
                "tttttt......tttttt",
                "tttttt......tttttt",
                "tttttt......tttttt",
                ".tttt........tttt.",
            ]},
            "boca_cerrada": {"x": 35, "y": 52, "filas": [
                "BBBB..BBBB",
                ".BBBBBBBB.",
                "....BB....",
            ]},
            "boca_abierta": {"x": 38, "y": 52, "filas": [
                "MMMM",
                "MMMM",
                ".MM.",
            ]},
        },
    },
}


def _validar_retratos() -> None:
    """Control de calidad del arte, al importar: mismo espíritu que el
    validador de ``Aventura`` — un retrato torcido explota acá con nombre y
    apellido, no como un pixel corrido en plena partida."""
    validos = set(PALETA) | {TRANSPARENTE}
    for nombre, retrato in RETRATOS.items():
        base = retrato["base"]
        if len(base) != ALTO or {len(f) for f in base} != {ANCHO}:
            raise ValueError(f"la base de {nombre!r} no mide {ANCHO}×{ALTO}")
        for numero, fila in enumerate(base):
            if TRANSPARENTE in fila:
                raise ValueError(f"la base de {nombre!r} tiene huecos (fila {numero})")
            if intrusos := set(fila) - validos:
                raise ValueError(f"la base de {nombre!r}, fila {numero}: chars {intrusos!r}")
        if faltan := set(CAPAS_DE_ANIMACION) - set(retrato["capas"]):
            raise ValueError(f"a {nombre!r} le faltan capas: {faltan}")
        for capa, datos in retrato["capas"].items():
            filas = datos["filas"]
            anchos = {len(f) for f in filas}
            if len(anchos) != 1:
                raise ValueError(f"{nombre!r}/{capa}: filas de anchos distintos: {anchos}")
            if intrusos := set("".join(filas)) - validos:
                raise ValueError(f"{nombre!r}/{capa}: chars {intrusos!r}")
            if datos["x"] + anchos.pop() > ANCHO or datos["y"] + len(filas) > ALTO:
                raise ValueError(f"{nombre!r}/{capa}: la capa se sale del retrato")


_validar_retratos()


# ── Export para la web ───────────────────────────────────────────────────────


def exportar_retratos() -> dict:
    """El paquete que viaja por ``GET /api/retratos``: paleta + capas, tal cual.

    La web no recibe imágenes: recibe estos mismos strings y pinta cada capa
    pixel por pixel en su <canvas> (ver ``estatico/js/pixelart.js``)."""
    return {
        "paleta": PALETA,
        "transparente": TRANSPARENTE,
        "ancho": ANCHO,
        "alto": ALTO,
        "retratos": RETRATOS,
    }
